### ISSUE TITLE
Change I2C address QMP6988

### ISSUE THREAD

**Issue by gunnm80** [m5stack/M5Unit-ENV#12]
Hi
I need some help. Am a newbie, I am trying to run multiple devices through a PaHub2 (SKU:U040-B) but I am having problems with the ENV3 sensor. Both the QMP6988 sensor and the PaHub2 use address 0x70. According to the QMP6988 datasheet, it has 2 addresses: 0x70 and 0x56. I have tried everything to make the QMP6988 communicate using address 0x56. But it always uses 0x70. Can someone please help me? What do I have to do to make QMP6988 work with address 0x56? Is it possible with a software like Arduino IDE? How exactly? Have a M5Stack ATOM Lite ESP32, M5StickC PLUS ESP32-PICO and a M5Stack AtomS3 Lite. Which one will work best with?
Thank you in advance. If I am not allowed to ask such questions here: please delete.
Greetings

**Comment by gunnm80** [comment]
can someone please help me? am really desperate....

**Comment by Tinyu-Zhao** [comment]
According to the data manual of QMP6988 and the schematic diagram of ENVIII, the I2C address of QMP6988 in our ENVIII is 0x70. Because the SDO pin is grounded, it is impossible to manually change the I2C address.

![image](https://github.com/m5stack/M5Unit-ENV/assets/44396641/9f3555bd-6136-45d9-a739-e1f548f1716f)

<img width="527" alt="image" src="https://github.com/m5stack/M5Unit-ENV/assets/44396641/1e46b57e-f000-4a03-914a-920f2e074d8a">

**Comment by MRobi1** [comment]
@gunnm80 were you ever able to make this work?
@Tinyu-Zhao is there any way to connect an ENVIII via the Pa.Hub at all?

**Comment by cpsoares** [comment]
I have the same issue. I believe the only way would be to change the Pa.Hub I2C address by fiddling with the A0..A2 jumpers on the Pa.Hub board. You would need to manually solder the jumper(s) according to your need, so it results on having PaHub responding on a dedicated I2C address on your bus. See here documentation for PaHub: https://docs.m5stack.com/en/unit/pahub2. Didn't test but I believe it will work.

**Comment by felmue** [comment]
Hi guys

as @cpsoares already stated it is possible to use ENV III unit(s) connected to a PaHUB unit if the I2C address of the PaHUB is modified via solder jumpers. I've tested this with UIFlow2.0.0 alpha-28. Please see [this](https://community.m5stack.com/topic/3963/pahub-enviii-pressure-reading-issue/7) forum thread.

Thanks
Felix

**Comment by felmue** [comment]
Hi @gunnm80 

unfortunately the I2C address of the QMP6988 cannot be changed by software.

That said it is possible to modify the I2C address with a hardware modification. I've actually added a jumper to my ENV III which allows me do set the I2C address manually. Please see [here](https://www.gwendesign.ch/kb/m5stack/enviii/).

Thanks
Felix
