### ISSUE TITLE
Examples for station

### ISSUE THREAD

**Issue by GeneralAdmin** [m5stack/M5Unit-ENV#14]
There is no example for station. There is any difference?

**Comment by Tinyu-Zhao** [comment]
I will add it.

**Comment by Tinyu-Zhao** [comment]
> There is no example for station. There is any difference?

Expect I2C pins

**Comment by Tinyu-Zhao** [comment]
https://github.com/Tinyu-Zhao/M5Unit-ENV/commit/cb49a08d7ea842de30d8d17624a9073d943b683b
