### ISSUE TITLE
Hat_ENVII_M5StickC.ino example breaking errors

### ISSUE THREAD

**Issue by GavinBeattie** [m5stack/M5Unit-ENV#16]
Stock run of the example above, taken from examples folder, results in these errors at compile and continuously reboots device. Serial monitor provided further down.

I get the same with Atom/Atom-Matrix and StickC using ENVII hat and ENVIII unit (ENV is fine). Thoughts welcome.

```
`/Users/.../Documents/Arduino/libraries/M5Unit-ENV/examples/Hat_ENVII_M5StickC/Hat_ENVII_M5StickC.ino: In function 'void loop()':
/Users/.../Documents/Arduino/libraries/M5Unit-ENV/examples/Hat_ENVII_M5StickC/Hat_ENVII_M5StickC.ino:45:11: error: request for member 'get' in 'sht30', which is of non-class type 'SHT3X()'
     sht30.get();           // Obtain the data of shT30.  获取sht30的数据
           ^~~
/Users/.../Documents/Arduino/libraries/M5Unit-ENV/examples/Hat_ENVII_M5StickC/Hat_ENVII_M5StickC.ino:46:17: error: request for member 'cTemp' in 'sht30', which is of non-class type 'SHT3X()'
     tmp = sht30.cTemp;     // Store the temperature obtained from shT30.
                 ^~~~~
/Users/.../Documents/Arduino/libraries/M5Unit-ENV/examples/Hat_ENVII_M5StickC/Hat_ENVII_M5StickC.ino:48:17: error: request for member 'humidity' in 'sht30', which is of non-class type 'SHT3X()'
     hum = sht30.humidity;  // Store the humidity obtained from the SHT30.
                 ^~~~~~~~

exit status 1

Compilation error: request for member 'get' in 'sht30', which is of non-class type 'SHT3X()'
`
```

And from serial monitor:
`17:16:45.191 -> Rebooting...
17:16:45.419 -> M5StickC initializing...OK
17:16:48.982 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
17:16:48.982 -> 
17:16:48.982 -> Core  1 register dump:
17:16:48.982 -> PC      : 0x400d3d73  PS      : 0x00060a30  A0      : 0x800d3ef7  A1      : 0x3ffb2750  
17:16:48.982 -> A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x00000000  
17:16:49.013 -> A6      : 0x00000000  A7      : 0x00000000  A8      : 0xfffe0000  A9      : 0x00000000  
17:16:49.013 -> A10     : 0x00000000  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00000000  
17:16:49.013 -> A14     : 0x00000000  A15     : 0xff000000  SAR     : 0x0000000f  EXCCAUSE: 0x0000001c  
17:16:49.013 -> EXCVADDR: 0x00000040  LBEG    : 0x400860e8  LEND    : 0x400860fe  LCOUNT  : 0xffffffff  
17:16:49.046 -> 
17:16:49.046 -> 
17:16:49.046 -> Backtrace: 0x400d3d70:0x3ffb2750 0x400d3ef4:0x3ffb2770 0x400d541c:0x3ffb2790 0x400d1603:0x3ffb27e0 0x400d702d:0x3ffb2820`

**Comment by kd8bxp** [comment]
try adding

`sht30.init();`

just below the 
`Wire.begin(32, 33);`
statement in void setup()

So it looks like this for the M5StickC
`
void setup() {

    M5.begin();             // Init M5StickC.  初始化 M5StickC

    M5.Lcd.setRotation(3);  // Rotate the screen.  旋转屏幕

    M5.Lcd.println(F("ENVII Unit(SHT30 and BMP280) test...\n"));

    Wire.begin(32, 33);  // Initialize pin 32,33.  初始化32,33引脚

    sht30.init();

}
`

or maybe like this for Atom:
`
void setup() {

    M5.begin(true, false, true);  // Init M5Atom.  初始化 M5Atom

    M5.dis.fillpix(0xFFFFE0);

    Wire.begin(26, 32);  // Initialize pin 26,32.  初始化26,32引脚

    Serial.println(F("ENV Unit(SHT30 and BMP280) test...\n"));

    sht30.init();

}
`

I'm using a M5StickC and got reboots until I added the sht30.init();  Probably the same for the Atom, but I haven't tried the atom.

**Comment by GavinBeattie** [comment]
Bravo, @kd8bxp.

For the StickC and ENVII hat example it needs the following change as well.
SHT3X sht30; // changed from SHT3X sht30(0x44, 1)

Swap the library out for Atom and comment out the LCD lines, works perfectly as well with the
sht30.init();
line straight after Wire.begin(26, 32); // Pins 19, 22 if using Atom-Mate and hats.

Two lines above need changed in the examples.
