### ISSUE TITLE
StickC + hat ENVII and StickC + unit ENVIII don't work

### ISSUE THREAD

**Issue by GavinBeattie** [m5stack/M5Unit-ENV#17]
examples/Hat_ENVII_M5StickC doesn't work (doesn't compile) error: candidate expects 0 arguments, 2 provided.
examples/Unit_ENVIII_M5StickC doesn't work gets stuck in rebooting loop after upload: Guru Meditation Error: Core 1 panic'ed (LoadProhibited). Exception was unhandled.

I have tried the above combinations following the installation guides to the letter from M5Stack StickC documents.
Mac, Windows Arduino v2 and RPi Arduino v1.

Are these examples out of step with this release? Can they be fixed please or highlighted in comments what libraries they are compatible with. Any community workarounds appreciated with descriptive summary of libraries utilised.

Update:

Dropped entire M5Unit-ENV library and replaced by add library in Arduino from ZIP from this fork
https://github.com/Tinyu-Zhao/M5Unit-ENV/

Examples tested:
StickC + ENVIII unit
StickC + ENVII hat
Atom Matrix + ENVII hat (even via Atom Mate with pins switched to 19, 22)
All working!

This is a bad break legacy staple ENVII and ENVIII common sensors not working with little to go on for fault finding.

**Comment by GavinBeattie** [comment]
Alt fix to using forked libraries:
SHT3X sht30; // Changed from SHT3X sht30(0x44, 1); to this.

Add
sht30.init();
under Wire.begin(32, 33);

Examples need revalidated for the latest libraries.

**Comment by JM-FRANCE** [comment]
Indeed,  this works with the M5StickC Plus

```
#include <M5StickCPlus.h>
#include "M5_ENV.h"

SHT3X sht30;
QMP6988 qmp6988;

float tmp      = 0.0;
float hum      = 0.0;
float pressure = 0.0;

void setup() {
  M5.begin();
  Wire.begin(0, 26); // M5 Stick C Plus (SDA, SCL)
  sht30.init();
  qmp6988.init();

  M5.Lcd.setRotation(3);
  M5.Lcd.setTextSize(3);
  M5.lcd.println(F("ENVIII test"));
}

void loop() {
  pressure = qmp6988.calcPressure();
  if (sht30.get() == 0) {  
    tmp = sht30.cTemp;  
    hum = sht30.humidity;
  } else {
    tmp = 0, hum = 0;
  }
  M5.Lcd.fillScreen(TFT_BLACK);
  M5.lcd.setCursor(0, 20);
  M5.Lcd.printf("T: %2.1f C  \r\nH: %2.0f%%  \r\nP:%2.0f HPa\r\n", tmp, hum, pressure / 100.0);
  delay(2000);
}
```

when used with a different M5 module you need to adjust the SCL and SDA GPIOs used for I2C
```
  Wire.begin(0, 26); // M5 Stick C Plus (SDA, SCL)
```

**Comment by Tinyu-Zhao** [comment]
You can update the library and try again.
