### ISSUE TITLE
Missing drivers for the Co2 Unit

### ISSUE THREAD

**Issue by dcflachs** [m5stack/M5Unit-ENV#19]
The latest version of this library mentions support for the CO2Unit and has examples for the same. It seems to be missing the SensirionI2CScd4x.h driver however.

**Comment by Gitshaoxiang** [comment]
https://github.com/Sensirion/arduino-i2c-scd4x
the Sensirion official seems not commit this lib to the arduino register lib. so you have to download the lib manual
