### ISSUE TITLE
ENVⅣ SHT4X not output

### ISSUE THREAD

**Issue by n-matsukawa** [m5stack/M5Unit-ENV#21]
Hello.
I purchased ENVⅣ and connected M5stackBasic2.7 to ENVⅣ with a gorve connector.
I am writing and testing the sample program ENV4.ino, but SHT4X is not output.
There is no output of "Couldn't find SHT4x" in the setup section, so there is no problem with communication.
thinking about.
However, the temperature, pressure, and altitude of BME280 are output within the loop,
The SHT4X part is not output at all.
Please tell me how to do it.

**Comment by felmue** [comment]
Hello @n-matsukawa 

I've encountered the same issue. I created a [PR](https://github.com/m5stack/M5Unit-ENV/pull/22/files) to fix the issue.

Thanks
Felix

**Comment by TheKursta** [comment]
Hi @n-matsukawa. Thank you for the fix! I encountered same issue when using Nano ESP32 Arduino board. Waiting for the new version to be published soon :). For now I edited Library source files with the listed changes and it works well!

**Comment by IvanKastorsky** [comment]
Hi, same here, I'm trying with M5StikC Plus2 and it didn't work neither sht40 nor bmp280

**Comment by IvanKastorsky** [comment]
> Hi, same here, I'm trying with M5StikC Plus2 and it didn't work neither sht40 nor bmp280

Sorry, I realized now that we need to change the pins in "sht4.begin()" from "21, 22" to "32, 33"

And yes, I've confirmed that the SHT40 only has output with the @felmue PR
