### ISSUE TITLE
Unit_ENVIII_AtomS3.ino needs to be modified

### ISSUE THREAD

**Issue by ttks01** [m5stack/M5Unit-ENV#25]
I tried to use Unit_ENVIII_AtomS3 but it doesn't work because the code is copied from ENV II unit, so now I'm using ENV_III.ino with changed SDA and SCL pin numbers in qmp.begin() and sht3x.begin(). I found a similar situation with Unit_ENVIII_M5Atom and Unit_ENVIII_M5AtomS3lite. Would you please fix these?

**Comment by Tinyu-Zhao** [comment]
I will check it.

**Comment by Tinyu-Zhao** [comment]
Sorry for the trouble, I have fixed the problem.
https://github.com/m5stack/M5Unit-ENV/commit/9bd122cdab04da5a4dc1450be06197ae850f0a3c

**Comment by ttks01** [comment]
Thank you for the quick fix.
